language: rust
cache: cargo
env:
  global:
    - RUST_BACKTRACE=1
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features
sudo: false
