language: python
python: "3.6"
env:
  global:
    - CARGO_HOME=$HOME/cargo
    - PATH=$HOME/cargo/bin:$PATH
    - RUST_BACKTRACE=1
    - RUSTUP_HOME=$HOME/rustup
before_install:
  - curl https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
  - cd argonautica-py
install:
  - pip install -r requirements-dev.txt
  - sudo -E -H echo $CARGO_HOME
  - sudo -E -H python setup.py bdist_wheel
  - ls dist
  - sudo -E -H pip install .
script:
  - cargo test --release --features="native simd serde"
  - cd argonautica-py && python3 -m unittest
sudo: true
