matrix:
  include:
    - language: python
      python:
        - "3.4"
        - "3.6"
      install:
        - pip install -r argonautica-py/requirements-dev.txt
        - pip install argonautica-py
      script:
        - cd argonautica-py && python -m unittest
    - language: rust
      rust:
        - stable
      cache: cargo
      env:
        global:
          - RUST_BACKTRACE=1
      script:
        - cargo test --release --features="native simd serde"
      sudo: false
