language: rust
cache: cargo
env:
  global:
    - RUST_BACKTRACE=1
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --release test_c_version -- --ignored --nocapture
sudo: false
