language: rust
env:
  global:
    - RUST_BACKTRACE=1
cache: cargo
# matrix:
  # allow_failures:
  #   - rust: nightly
  # fast_finish: true
rust:
  - stable
before_install:
  - apt-get install python3 -y
  - cd argonautica-py
install:
  - pip3 install -r requirements-dev.txt
  - python3 setup.py bdist_wheel
  - pip3 install .
script:
  - cargo test --release --features="native simd serde"
  - cd argonautica-py && python3 -m unittest
sudo: true
