env:
  global:
    - CARGO_HOME=$HOME/cargo
    - PATH=$HOME/cargo/bin:$PATH
    - RUST_BACKTRACE=1
    - RUSTUP_HOME=$HOME/rustup
matrix:
  include:
    - language: python
      python: "3.6"
      install:
        - curl https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - pip install --upgrade pip
        - pip install argon2_cffi passlib
        - pip install setuptools-rust
        - python setup.py sdist
        - pip uninstall setuptools-rust -y
        - pip install dist/argonautica-0.1.5.tar.gz
      script:
        - cd argonautica-py
        - python -m unittest
        - python benchmark.py
        - python examples/argon2.py
        - python examples/configuration.py
        - python examples/configuration2.py
        - python examples/configuration3.py
        - python examples/hash_raw.py
        - python examples/hasher.py
        - python examples/random_salt.py
        - python examples/verifier.py
    - language: python
      python: "3.5"
      install:
        - curl https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - pip install --upgrade pip
        - pip install argon2_cffi passlib
        - pip install setuptools-rust
        - python setup.py sdist
        - pip uninstall setuptools-rust -y
        - pip install dist/argonautica-0.1.5.tar.gz
      script:
        - cd argonautica-py
        - python -m unittest
        - python benchmark.py
        - python examples/argon2.py
        - python examples/configuration.py
        - python examples/configuration2.py
        - python examples/configuration3.py
        - python examples/hash_raw.py
        - python examples/hasher.py
        - python examples/random_salt.py
        - python examples/verifier.py
    - language: python
      python: "3.4"
      install:
        - curl https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - pip install --upgrade pip
        - pip install argon2_cffi passlib
        - pip install setuptools-rust
        - python setup.py sdist
        - pip uninstall setuptools-rust -y
        - pip install dist/argonautica-0.1.5.tar.gz
      script:
        - cd argonautica-py
        - python -m unittest
        - python benchmark.py
        - python examples/argon2.py
        - python examples/configuration.py
        - python examples/configuration2.py
        - python examples/configuration3.py
        - python examples/hash_raw.py
        - python examples/hasher.py
        - python examples/random_salt.py
        - python examples/verifier.py
    - language: python
      python: "pypy3.5"
      install:
        - curl https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - pip install --upgrade pip
        - pip install --upgrade setuptools
        - pip install wheel
        - pip install argon2_cffi passlib
        - pip install setuptools-rust
        - python setup.py sdist
        - pip uninstall setuptools-rust -y
        - pip install dist/argonautica-0.1.5.tar.gz
      script:
        - cd argonautica-py
        - python -m unittest
        - python benchmark.py
        - python examples/argon2.py
        - python examples/configuration.py
        - python examples/configuration2.py
        - python examples/configuration3.py
        - python examples/hash_raw.py
        - python examples/hasher.py
        - python examples/random_salt.py
        - python examples/verifier.py
    - language: rust
      rust: stable
      cache: cargo
      script:
        - cd argonautica-rs
        - cargo test --release --features="simd serde"
        - cd ../argonautica-c
        - cargo test --release --features="simd"
    - language: rust
      rust: 1.31.0
      cache: cargo
      script:
        - cd argonautica-rs
        - cargo test --release --features="simd serde"
        - cd ../argonautica-c
        - cargo test --release --features="simd"

sudo: false
dist: trusty
