env:
  global:
    - CARGO_HOME=$HOME/cargo
    - PATH=$HOME/cargo/bin:$PATH
    - RUST_BACKTRACE=1
    - RUSTUP_HOME=$HOME/rustup
matrix:
  include:
    - language: python
      python: "3.6"
      install:
        - curl https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - pip install --upgrade pip
        - pip install argon2_cffi passlib
        - pip install setuptools-rust
        - python setup.py sdist
        - pip install dist/argonautica-0.1.0.tar.gz
      script:
        - cd argonautica-py
        - python -m unittest
        - python benchmark.py
    - language: python
      python: "3.5"
      install:
        - curl https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - pip install --upgrade pip
        - pip install argon2_cffi passlib
        - pip install setuptools-rust
        - python setup.py sdist
        - pip install dist/argonautica-0.1.0.tar.gz
      script:
        - cd argonautica-py
        - python -m unittest
        - python benchmark.py
    - language: python
      python: "3.4"
      install:
        - curl https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - pip install --upgrade pip
        - pip install argon2_cffi passlib
        - pip install setuptools-rust
        - python setup.py sdist
        - pip install dist/argonautica-0.1.0.tar.gz
      script:
        - cd argonautica-py
        - python -m unittest
        - python benchmark.py
    - language: python
      python: "pypy3.5"
      install:
        - curl https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - pip install --upgrade pip
        - pip install --upgrade setuptools
        - pip install wheel
        - pip install argon2_cffi passlib
        - pip install setuptools-rust
        - python setup.py sdist
        - pip install dist/argonautica-0.1.0.tar.gz
      script:
        - cd argonautica-py
        - python -m unittest
        - python benchmark.py
    - language: rust
      rust: stable
      cache: cargo
      script:
        - cargo test --release --features="simd serde" -p argonautica
        - cargo test --release --features="simd" -p argonautica-c -- --nocapture
sudo: false
dist: trusty
