env:
  global:
    - CARGO_HOME=$HOME/cargo
    - PATH=$HOME/cargo/bin:$PATH
    - RUST_BACKTRACE=1
    - RUSTUP_HOME=$HOME/rustup
matrix:
  include:
    - language: python
      python: "3.6"
      install:
        - curl https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - git clone https://github.com/bcmyers/setuptools-rust.git
        - cd setuptools-rust && pip install . && cd ..
        - python setup.py sdist
        - pip install dist/argonautica-0.1.0.tar.gz
      script:
        - cd argonautica-py
        - python -m unittest
    - language: python
      python: "3.5"
      install:
        - curl https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - git clone https://github.com/bcmyers/setuptools-rust.git
        - cd setuptools-rust && pip install . && cd ..
        - python setup.py sdist
        - pip install dist/argonautica-0.1.0.tar.gz
      script:
        - cd argonautica-py
        - python -m unittest
    - language: python
      python: "3.4"
      install:
        - curl https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - git clone https://github.com/bcmyers/setuptools-rust.git
        - cd setuptools-rust && pip install . && cd ..
        - python setup.py sdist
        - pip install dist/argonautica-0.1.0.tar.gz
      script:
        - cd argonautica-py
        - python -m unittest
    - language: python
      python: "pypy3.5"
      install:
        - curl https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - pip install --upgrade setuptools
        - pip install wheel
        - git clone https://github.com/bcmyers/setuptools-rust.git
        - cd setuptools-rust && pip install . && cd ..
        - python setup.py sdist
        - pip install dist/argonautica-0.1.0.tar.gz
      script:
        - cd argonautica-py
        - python -m unittest
    - language: rust
      rust: stable
      cache: cargo
      script:
        - cargo test --release --features="simd serde"
sudo: false
dist: trusty
