matrix:
  include:
    - language: python
      python:
        - "3.4"
        - "3.6"
      before_install: cd argonautica-py
      install:
        - pip install -r requirements-dev.txt
        - python setup.py bdist_wheel
        - pip install .
      before_script: cd argonautica-py
      script:
        - python -m unittest
    - language: rust
      cache: cargo
      env:
        global:
          - RUST_BACKTRACE=1
      script:
        - cargo test --release --features="native simd serde"
      sudo: false
