version: '3'
services:
  rust:
    command: bash -c "cargo test --features serde"
    build: .
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - .:/home/dev/a2
      - target:/home/dev/a2/target
    working_dir: /home/dev/a2

volumes:
  target:

