version: '3'
services:
  tests:
    command: bash -c "cargo test --release --features serde -- --nocapture"
    build: .
    environment:
      - LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu/
      - RUST_BACKTRACE=1
    volumes:
      - .:/home/dev/jasonus
      - target:/home/dev/jasonus/target
    working_dir: /home/dev/jasonus

volumes:
  target:
