[package]
name = "a2py"
version = "0.1.0" # remember to update html_root_url

authors = ["Brian Myers <brian.carl.myers@gmail.com>"]
license = "MIT/Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
a2 = { path = "../../a2" }
