[package]
name = "argonautica-py"
version = "0.1.0"

authors = ["Brian Myers <brian.carl.myers@gmail.com>"]
license = "MIT/Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
argonautica = { path = "../../argonautica-rs" } # TODO: Hack
